version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nr-databind-core
    versions:
    - ">= 0.0.a"
    - "< 0.1"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule: 
   interval: daily
  open-pull-requests-limit: 10
