coverage:
  precision: 0
  round: down
  status:
    patch:
      default:
        target: 90
        informational: true
    project:
      default:
        threshold: 1%
        informational: true
    changes: false
comment: false
ignore:
  - "tests/"
github_checks:
  # TODO(epwalsh): re-enable if there is a way to only enable annotations
  # on diff lines for a PR.
  annotations: false
