coverage:
  precision: 0
  round: down
  status:
    patch:
      default:
        target: 90
    project:
      default:
        threshold: 1%
    changes: false
comment: false
ignore:
  - "allennlp/tests"
  - "allennlp/tools/squad_eval.py"
  - "allennlp/tools/wikitables_evaluator.py"
