apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: allennlp-webdemo
  namespace: allennlp
  labels:
    contact: allennlp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: allennlp-webdemo
    spec:
      containers:
        - name: allennlp-webdemo
          image: "allennlp/allennlp:latest"
          # See
          # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
          # for documentation on the resources section.
          resources:
            limits:
              # One-half of a CPU.
              cpu: 500m
              # 500 megabytes.
              memory: 1000Mi
            # "requests" specify how much your container will be granted as a baseline.
            requests:
              # One-fifth of a CPU.
              cpu: 200m
              # 250 megabytes.
              memory: 1000Mi
          command:
            - /bin/bash
            - -c
            - "source activate allennlp && allennlp/run serve"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: allennlp-webdemo
  namespace: allennlp
spec:
  type: LoadBalancer
  selector:
    app: allennlp-webdemo
  ports:
    - port: 80
      targetPort: 8000
