apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: allennlp-webdemo
  namespace: allennlp
  labels:
    contact: allennlp
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: allennlp-webdemo
    spec:
      containers:
        - name: allennlp-webdemo
          image: "allennlp/webdemo:2017-09-12-2"
          # See
          # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
          # for documentation on the resources section.
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            # "requests" specify how much your container will be granted as a baseline.
            requests:
              cpu: 1000m
              memory: 2000Mi
          command:
            - /bin/bash
            - -c
            - "source activate allennlp && allennlp/run serve"
---
apiVersion: v1
kind: Service
metadata:
  name: allennlp-webdemo
  namespace: allennlp
spec:
  type: LoadBalancer
  selector:
    app: allennlp-webdemo
  ports:
    - port: 80
      targetPort: 8000
