#!/usr/bin/env python
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(os.path.join(__file__, os.pardir))))

from allennlp.commands.main import main

if __name__ == "__main__":
    # sys.argv[0] is the name of the script, throw it away
    main(sys.argv[1:])
