# Beaker configuration file for training the BiDAF model.
description: ALLENNLP_VERSION, ALLENNLP_MODELS_VERSION
tasks:
  - name: bidaf-training
    spec:
      image: IMAGE_NAME
      resultPath: /output
      args:
        - train
        - https://raw.githubusercontent.com/allenai/allennlp/master/scripts/benchmarks/configs/bidaf.jsonnet
        - -s
        - /output
        - --file-friendly-logging
      requirements:
        gpuCount: 1
    cluster: ai2/on-prem-ai2-server1
