from allennlp.models.encoder_decoders.simple_seq2seq import SimpleSeq2Seq
from allennlp.models.encoder_decoders.wikitables.wikitables_semantic_parser import WikiTablesSemanticParser
from allennlp.models.encoder_decoders.nlvr.nlvr_semantic_parser import NlvrSemanticParser
