from allennlp.modules.similarity_functions.bilinear import Bilinear
from allennlp.modules.similarity_functions.dot_product import DotProduct
from allennlp.modules.similarity_functions.linear import Linear
from allennlp.modules.similarity_functions.cosine_similarity import CosineSimilarity
