name: Benchmarks

on:
  schedule:
  - cron: '31 8 * * 1,2,3,4,5'  # early morning (8:31 UTC / 1:31 AM PDT) Monday - Friday

jobs:
  beaker:
    name: Submit Beaker Jobs
    # Only run on main repo.
    if: github.repository == 'allenai/allennlp'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install beaker
      run: |
        wget https://github.com/allenai/beaker/releases/download/v20200430/beaker_linux.tar.gz
        sudo tar -xvzf beaker_linux.tar.gz -C /usr/local/bin

    - name: Configure beaker
      run: |
        beaker config set user_token ${{ secrets.BEAKER_TOKEN }}
        beaker config test

    - name: Set environment variables
      run: |
        ALLENNLP_COMMIT=$GITHUB_SHA
        ALLENNLP_MODELS_COMMIT=$(git ls-remote https://github.com/allenai/allennlp-models.git | head -1 | sed 's/HEAD//')
        IMAGE_NAME="allennlp-with-models-$ALLENNLP_COMMIT"

        echo "::set-env name=ALLENNLP_COMMIT::$ALLENNLP_COMMIT";
        echo "::set-env name=ALLENNLP_MODELS_COMMIT::$ALLENNLP_MODELS_COMMIT";
        echo "::set-env name=IMAGE_NAME::$IMAGE_NAME";

    - name: Update beaker configs for latest commit
      run: |
        for config in scripts/benchmarks/configs/*.yml; do
            echo "Found config: $config";
            sed -i "s/ALLENNLP_COMMIT/$ALLENNLP_COMMIT/g" $config;
            sed -i "s/IMAGE_NAME/$IMAGE_NAME/g" $config;
        done

    - name: Pull dockerfile
      run: |
        wget https://raw.githubusercontent.com/allenai/allennlp-models/master/Dockerfile.commit

    - name: Debugging info
      run: |
        echo "AllenNLP commit: $ALLENNLP_COMMIT"
        echo "AllenNLP Models commit: $ALLENNLP_MODELS_COMMIT"

        echo "Dockerfile:"
        cat Dockerfile.commit

    - name: Build image
      run: |
        docker build \
            --build-arg ALLENNLP_COMMIT=$ALLENNLP_COMMIT \
            --build-arg ALLENNLP_MODELS_COMMIT=$ALLENNLP_MODELS_COMMIT \
            -t $IMAGE_NAME - < Dockerfile.commit

    - name: Upload image to beaker
      run: |
        beaker image create -n $IMAGE_NAME $IMAGE_NAME

    - name: Submit beaker experiments
      run: |
        for config in scripts/benchmarks/configs/*.yml; do
            experiment_name=${config//+(*\/|.yml)}_$(date -u +%Y%m%d);
            echo "Submitting $experiment_name to beaker";
            beaker experiment create --name $experiment_name -f $config --workspace ai2/AllenNLPPerf;
        done
