name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        # Create a small context for the Docker with only the files that we need.
        tar -czvf context.tar.gz Dockerfile.pip scripts/ai2_internal/resumable_train.sh
        docker build \
            --pull \
            --build-arg SOURCE_COMMIT=$GITHUB_SHA \
            -f Dockerfile.pip \
            -t allennlp/commit:$GITHUB_SHA - < context.tar.gz

    - name: Test image
      run: |
        docker run --rm allennlp/commit:$GITHUB_SHA test-install

    - name: Push image
      # Only run on "allenai/allennlp", not forks.
      if: github.repository == 'allenai/allennlp'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        # TODO:
        # docker push allennlp/commit:$GITHUB_SHA
