name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']

    steps:
    - uses: actions/checkout@v1

    - &setup_python
      name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - &restore_cache
      uses: actions/cache@v1
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pydeps-${{ matrix.python }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pydeps-${{ matrix.python }}

    - &install_deps
      name: Install requirements
      run: |
        pip install -e .
        pip install --upgrade -r dev-requirements.txt

    - &debug
      name: Debug info
      run: |
        pip freeze

    - name: Lint
      run: |
        make lint

    - name: Type check
      run: |
        make typecheck

    - name: Run tests
      run: |
        make test-with-cov

    # TODO: remove codecov report publishing from TeamCity build and then uncomment this:
    # - name: Upload coverage to Codecov
    #   # Only run for one python version.
    #   if: matrix.python == '3.7'
    #   uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}

  models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']

    steps:
    - uses: actions/checkout@v1

    - *setup_python
    - *restore_cache
    - *install_deps
    - *debug

    - name: Pull and install models repo
      env:
        EXCLUDE_ALLENNLP_IN_SETUP: "true"
      run: |
        git clone https://github.com/allenai/allennlp-models.git
        cd allennlp-models && pip install -e . && pip install -r dev-requirements.txt

    - name: Run models tests
      run: |
        cd allennlp-models && make test

    - name: Clean up
      run: |
        pip uninstall allennlp_models
