name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-deps-${{ matrix.python }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-deps-${{ matrix.python }}

    - name: Install requirements
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install -e .
        pip install --upgrade -r dev-requirements.txt

    - name: Show pip freeze
      run: |
        . .venv/bin/activate
        pip freeze

    - name: Check for large files
      run: |
        ./scripts/check_large_files.sh 2

    - name: Lint
      run: |
        . .venv/bin/activate
        make lint

    - name: Type check
      run: |
        . .venv/bin/activate
        make typecheck

    - name: Run tests
      run: |
        . .venv/bin/activate
        PATH=.venv/bin:$PATH make test-with-cov

    # TODO: remove codecov report publishing from TeamCity build and then uncomment this:
    # - name: Upload coverage to Codecov
    #   if: matrix.python == '3.7'
    #   run: |
    #     . .venv/bin/activate
    #     codecov
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
